### ISSUE TITLE
Book a moving truck

### ISSUE THREAD

**Issue by metadolphin** [metadolphin/OrangeWing#13]
Assuming you're moving into an unfurnished place, get quotes on moving trucks 
- [x] Pick load-up date in Portland
- [x] Pick unload/arrival in CA date
- [ ] Evaluate how much furniture & boxes you have

**Comment by prismofeverything** [comment]
Loading the truck on the 5th of July
Driving the truck to California on the 6th of July
Arriving/Unloading the truck on the 7th of July

**Comment by metadolphin** [comment]
SUCCESS!!! YAY!
